export const samplePrompts = [
  "What are the notes in a C major scale?",
  "How do you construct a G major chord?",
  "What is the harmonic minor scale for A minor?",
  "Can you show the intervals of a perfect fifth on the staff?",
  "How do you notate a D7 chord?",
  "What are the notes in an F major scale?",
  "How do you write a B diminished chord?",
  "What is the melodic minor scale for E minor?",
  "Can you show the intervals of a major third on the staff?",
  "How do you notate an A minor chord?",
  "What are the notes in a Bb major scale?",
  "How do you construct an E major chord?",
  "What is the natural minor scale for D minor?",
  "Can you show the intervals of a minor seventh on the staff?",
  "How do you write a C# minor chord?",
  "What are the notes in an Ab major scale?",
  "How do you notate a G augmented chord?",
  "What is the harmonic minor scale for B minor?",
  "Can you show the intervals of a diminished fifth on the staff?",
  "How do you write an F# major chord?",
  "What are the notes in a D major scale?",
  "How do you construct a C major 7 chord?",
  "What is the melodic minor scale for G minor?",
  "Can you show the intervals of a major sixth on the staff?",
  "How do you notate an E minor 7 chord?",
  "What are the notes in an Eb major scale?",
  "How do you write an A diminished chord?",
  "What is the natural minor scale for C minor?",
  "Can you show the intervals of a minor third on the staff?",
  "How do you notate a B major chord?",
  "What are the notes in a F# major scale?",
  "How do you construct a D minor 7 chord?",
  "What is the harmonic minor scale for F minor?",
  "Can you show the intervals of a perfect fourth on the staff?",
  "How do you write a G# minor chord?",
  "What are the notes in a Db major scale?",
  "How do you notate an F augmented chord?",
  "What is the melodic minor scale for Bb minor?",
  "Can you show the intervals of a major seventh on the staff?",
  "How do you write an E major 7 chord?",
  "What are the notes in a B major scale?",
  "How do you construct an Ab minor chord?",
  "What is the natural minor scale for Eb minor?",
  "Can you show the intervals of a minor sixth on the staff?",
  "How do you notate a C minor 7 chord?",
  "What are the notes in a Gb major scale?",
  "How do you write a D augmented chord?",
  "What is the harmonic minor scale for C# minor?",
  "Can you show the intervals of a major second on the staff?",
  "How do you notate an F# minor chord?",
  "What are the notes in a C# major scale?",
];
